package model;

public enum PropertyName {
    HAS_WON_THE_GAME , HAS_LOST_THE_GAME  , VALIDATOR_RESULT, NEXT_ROUND, UNDO_A_VALIDATOR_TEST, UNDO,
    REDO, UN_ENTER_A_CODE,REDO_ENTER_A_CODE, UNDO_A_NEXT_ROUND;
}
